abort.o : \
	utils.o 

array_utils.o : \
	abort.o \
	utils.o 

calculate.o : \
	settings.o \
	utils.o 

chordal_sampling.o : \
	calculate.o \
	random_utils.o \
	settings.o \
	utils.o 

clustering.o : \
	calculate.o \
	run_time_info.o \
	settings.o \
	abort.o \
	utils.o 

feedback.o : \
	run_time_info.o \
	settings.o \
	read_write.o \
	utils.o 

generate.o : \
	mpi_utils.o \
	abort.o \
	array_utils.o \
	feedback.o \
	read_write.o \
	calculate.o \
	random_utils.o \
	run_time_info.o \
	settings.o \
	utils.o 

ini.o : \
	array_utils.o \
	abort.o \
	read_write.o \
	params.o \
	settings.o \
	priors.o \
	utils.o 

interfaces.o : \
	read_write.o \
	params.o \
	ini.o \
	mpi_utils.o \
	nested_sampling.o \
	random_utils.o \
	settings.o \
	utils.o 

mpi_utils.o : \
	abort.o \
	utils.o 

nested_sampling.o : \
	generate.o \
	clustering.o \
	random_utils.o \
	chordal_sampling.o \
	run_time_info.o \
	feedback.o \
	read_write.o \
	settings.o \
	mpi_utils.o \
	utils.o 

params.o : \
	utils.o 

priors.o : \
	abort.o \
	array_utils.o \
	params.o \
	settings.o \
	utils.o 

random_utils.o : \
	mpi_utils.o \
	utils.o 

read_write.o : \
	params.o \
	priors.o \
	abort.o \
	run_time_info.o \
	settings.o \
	utils.o 

run_time_info.o : \
	calculate.o \
	random_utils.o \
	array_utils.o \
	settings.o \
	utils.o 

settings.o : \
	abort.o \
	utils.o 

utils.o : 
