# Utility targets
.PHONY: clean veryclean

clean:
	$(MAKE) -C examples clean
	$(MAKE) -C fortran clean
	$(MAKE) -C CC clean

veryclean: clean
	$(MAKE) -C examples veryclean
	$(MAKE) -C fortran veryclean
	$(MAKE) -C CC veryclean
