        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 25 17:09:20 2015
        MODULE LOGLIKELIHOOD__genmod
          INTERFACE 
            FUNCTION LOGLIKELIHOOD(THETA,PHI,CONTEXT)
              REAL(KIND=8), INTENT(IN) :: THETA(:)
              REAL(KIND=8), INTENT(OUT) :: PHI(:)
              INTEGER(KIND=4), INTENT(IN) :: CONTEXT
              REAL(KIND=8) :: LOGLIKELIHOOD
            END FUNCTION LOGLIKELIHOOD
          END INTERFACE 
        END MODULE LOGLIKELIHOOD__genmod
