name: check_version
on: [push, pull_request]
jobs:
  check_version_numbers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set environment
      run: |
      echo "fortran_version=$(grep 'version' src/polychord/feedback.f90 | grep -oe '[0-9]\+\.[0-9]\+\.[0-9]');" >> $GITHUB_ENV
      echo "python_version=$(grep '__version__' pypolychord/__init__.py | grep -oe '[0-9]\+\.[0-9]\+\.[0-9]')" >> $GITHUB_ENV
      echo "readme_version=$(grep 'PolyChord v' README.rst | grep -oe '[0-9]\+\.[0-9]\+\.[0-9]')" >> $GITHUB_ENV
    - name: Check python matches fortran version number
      run: [ $python_version = $fortran_version ]
    - name: Check fortran matches readme version number
      run: [ $fortran_version = $readme_version ]
    - name: Check readme matches fortran version number
      run: [ $readme_version = $fortran_version ]
